language: node_js
cache: npm
jobs:
  include:
    - stage: Build
      script: npm run build
    - stage: Code style check
      name: ESLint
      script: npm run lint
    - name: Prettier
      script: npm run prettier-check
