name: Publish to NPM

on:
  push:
    branches: [release]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
          registry-url: https://registry.npmjs.org/

      - name: Install deps
        run: npm ci

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
